/*
 * seg3_cross.c -- segment 3 padding-oracle search over the two key halves.
 *
 * Segment 3's AES-256 key is clue3 (8 characters) || clue7 (24 characters).
 * The plaintext is one block: 8 useful bytes followed by PKCS7 padding of
 * eight 0x08 bytes, so a key is correct iff
 *
 *     D(ct)[i] XOR iv[i] == 0x08   for i = 8..15
 *
 * That is a 64-bit condition on the output of one AES-256 block decryption.
 * The round function does not separate across the two halves of the key, so
 * there is no algebraic shortcut and the search is brute force.
 *
 * WHY THIS TOOL EXISTS. Clue 3 is closed as a source of new readings
 * (tools/clue3_closure.py: the printed digits are redundant on all 96 arrow
 * cells, the 92-cycle string hides no message, and every 8-character extraction
 * consistent with the step-size semantics has been enumerated). So the only way
 * to test a clue-7 candidate ON ITS OWN is to let the clue-3 half range over
 * everything it could be. Earlier runs let it range over {w,a,s,d}^8 (65,536)
 * and {0-9}^8 (100,000,000). Neither contains a MIXED answer, and all 1,290
 * retained clue-3 readings are mixed -- including the repo's own strongest,
 * `d3w1as24`, which needs letters and digits. Every clue-7 negative in rounds
 * 14-20 was therefore computed against a clue-3 space that could not have held
 * the answers it was testing for.
 *
 * This tool sweeps the full
 *
 *     "wasd0123456789" ^ 8 = 1,475,789,056
 *
 * so a clue-7 candidate that fails here is refuted UNCONDITIONALLY, rather than
 * conditionally on a clue-3 reading being right.
 *
 * Modes
 *   list  <witness-file> <lefts> <rights>
 *          cross product of two files, one string per line. Every pair is a
 *          real candidate pair, so a hit names both halves.
 *   alpha <witness-file> <rights> [max_rights]
 *          for each right, sweep the clue-3 half over the full alphabet above.
 *   pt    <keys>
 *          print key and full plaintext for each 32-char key line, so an
 *          external implementation can be compared byte for byte.
 *
 * Witness protocol. Both searching modes take a witness file generated by
 * tools/seg3_witnesses.py using pycryptodome, and re-check every witness
 * before the sweep starts. A run that cannot re-find them prints UNCERTIFIED
 * and its negatives do not count. Witness keys are drawn from the streams
 * actually swept, so a hit inside a real family is guaranteed re-findable by
 * that same run.
 *
 * This file contains DECRYPTION ONLY. An earlier version also carried a forward
 * cipher in order to plant witnesses in-process; its decrypt agreed with
 * pycryptodome while its encrypt did not, so the forward cipher was removed
 * rather than trusted. Witness generation now lives in
 * tools/seg3_witnesses.py, which shares no code with this file.
 *
 * usage
 *   seg3_cross selftest
 *   seg3_cross pt    <keys.txt>
 *   seg3_cross list  <witnesses.txt> <lefts.txt> <rights.txt>
 *   seg3_cross alpha <witnesses.txt> <rights.txt> [max_rights]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* ------------------------------------------------- AES-256 tables (FIPS-197)
   Copied verbatim from the verified tools/sweep.c. `selftest` re-derives the
   S-box from its definition (multiplicative inverse in GF(2^8) plus the
   affine map) and requires all 256 bytes to match, so a transcription slip
   cannot pass silently. */
static const uint8_t SBOX[256] = {
0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,
0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,
0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,
0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,
0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,
0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,
0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,
0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,
0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,
0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,
0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,
0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,
0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,
0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,
0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,
0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16};
static const uint8_t ISBOX[256] = {
0x52,0x09,0x6a,0xd5,0x30,0x36,0xa5,0x38,0xbf,0x40,0xa3,0x9e,0x81,0xf3,0xd7,0xfb,
0x7c,0xe3,0x39,0x82,0x9b,0x2f,0xff,0x87,0x34,0x8e,0x43,0x44,0xc4,0xde,0xe9,0xcb,
0x54,0x7b,0x94,0x32,0xa6,0xc2,0x23,0x3d,0xee,0x4c,0x95,0x0b,0x42,0xfa,0xc3,0x4e,
0x08,0x2e,0xa1,0x66,0x28,0xd9,0x24,0xb2,0x76,0x5b,0xa2,0x49,0x6d,0x8b,0xd1,0x25,
0x72,0xf8,0xf6,0x64,0x86,0x68,0x98,0x16,0xd4,0xa4,0x5c,0xcc,0x5d,0x65,0xb6,0x92,
0x6c,0x70,0x48,0x50,0xfd,0xed,0xb9,0xda,0x5e,0x15,0x46,0x57,0xa7,0x8d,0x9d,0x84,
0x90,0xd8,0xab,0x00,0x8c,0xbc,0xd3,0x0a,0xf7,0xe4,0x58,0x05,0xb8,0xb3,0x45,0x06,
0xd0,0x2c,0x1e,0x8f,0xca,0x3f,0x0f,0x02,0xc1,0xaf,0xbd,0x03,0x01,0x13,0x8a,0x6b,
0x3a,0x91,0x11,0x41,0x4f,0x67,0xdc,0xea,0x97,0xf2,0xcf,0xce,0xf0,0xb4,0xe6,0x73,
0x96,0xac,0x74,0x22,0xe7,0xad,0x35,0x85,0xe2,0xf9,0x37,0xe8,0x1c,0x75,0xdf,0x6e,
0x47,0xf1,0x1a,0x71,0x1d,0x29,0xc5,0x89,0x6f,0xb7,0x62,0x0e,0xaa,0x18,0xbe,0x1b,
0xfc,0x56,0x3e,0x4b,0xc6,0xd2,0x79,0x20,0x9a,0xdb,0xc0,0xfe,0x78,0xcd,0x5a,0xf4,
0x1f,0xdd,0xa8,0x33,0x88,0x07,0xc7,0x31,0xb1,0x12,0x10,0x59,0x27,0x80,0xec,0x5f,
0x60,0x51,0x7f,0xa9,0x19,0xb5,0x4a,0x0d,0x2d,0xe5,0x7a,0x9f,0x93,0xc9,0x9c,0xef,
0xa0,0xe0,0x3b,0x4d,0xae,0x2a,0xf5,0xb0,0xc8,0xeb,0xbb,0x3c,0x83,0x53,0x99,0x61,
0x17,0x2b,0x04,0x7e,0xba,0x77,0xd6,0x26,0xe1,0x69,0x14,0x63,0x55,0x21,0x0c,0x7d};
static uint8_t MUL1[256],MUL2[256],MUL3[256],MUL9[256],MUL11[256],MUL13[256],MUL14[256];

static void build_tables(void){
    for(int x=0;x<256;x++) MUL1[x]=(uint8_t)((x<<1)^((x&0x80)?0x1b:0));
    for(int x=0;x<256;x++){ MUL2[x]=MUL1[MUL1[x]]; MUL3[x]=(uint8_t)(MUL1[x]^x); }
    for(int x=0;x<256;x++){
        uint8_t m8=MUL1[MUL2[x]];
        MUL9[x] =(uint8_t)(m8^x);
        MUL11[x]=(uint8_t)(m8^MUL1[x]^x);
        MUL13[x]=(uint8_t)(m8^MUL2[x]^x);
        MUL14[x]=(uint8_t)(m8^MUL2[x]^MUL1[x]);
    }
}
static void aes256_expand(const uint8_t*key,uint8_t*rk){
    static const uint8_t RCON[11]={0,0x01,0x02,0x04,0x08,0x10,0x20,0x40,0x80,0x1b,0x36};
    memcpy(rk,key,32);
    for(int i=8;i<60;i++){
        uint8_t t[4]={rk[4*i-4],rk[4*i-3],rk[4*i-2],rk[4*i-1]};
        if(i%8==0){ uint8_t tmp=t[0]; t[0]=(uint8_t)(SBOX[t[1]]^RCON[i/8]); t[1]=SBOX[t[2]]; t[2]=SBOX[t[3]]; t[3]=SBOX[tmp]; }
        else if(i%8==4){ for(int a=0;a<4;a++) t[a]=SBOX[t[a]]; }
        rk[4*i  ]=(uint8_t)(rk[4*(i-8)  ]^t[0]);
        rk[4*i+1]=(uint8_t)(rk[4*(i-8)+1]^t[1]);
        rk[4*i+2]=(uint8_t)(rk[4*(i-8)+2]^t[2]);
        rk[4*i+3]=(uint8_t)(rk[4*(i-8)+3]^t[3]);
    }
}
static void inv_shift_sub(const uint8_t*s,uint8_t*u){
    u[0]=ISBOX[s[0]];  u[4]=ISBOX[s[4]];  u[8]=ISBOX[s[8]];   u[12]=ISBOX[s[12]];
    u[1]=ISBOX[s[13]]; u[5]=ISBOX[s[1]];  u[9]=ISBOX[s[5]];   u[13]=ISBOX[s[9]];
    u[2]=ISBOX[s[10]]; u[6]=ISBOX[s[14]]; u[10]=ISBOX[s[2]];  u[14]=ISBOX[s[6]];
    u[3]=ISBOX[s[7]];  u[7]=ISBOX[s[11]]; u[11]=ISBOX[s[15]]; u[15]=ISBOX[s[3]];
}
static void inv_mix_cols(uint8_t*a,uint8_t*b){
    b[0]=(uint8_t)(MUL14[a[0]]^MUL11[a[1]]^MUL13[a[2]]^MUL9 [a[3]]);
    b[1]=(uint8_t)(MUL9 [a[0]]^MUL14[a[1]]^MUL11[a[2]]^MUL13[a[3]]);
    b[2]=(uint8_t)(MUL13[a[0]]^MUL9 [a[1]]^MUL14[a[2]]^MUL11[a[3]]);
    b[3]=(uint8_t)(MUL11[a[0]]^MUL13[a[1]]^MUL9 [a[2]]^MUL14[a[3]]);
}
static void aes256_decrypt_block(const uint8_t*rk,const uint8_t*in,uint8_t*out){
    uint8_t s[16],u[16],t[16];
    memcpy(s,in,16);
    for(int i=0;i<16;i++) s[i]^=rk[224+i];
    for(int r=13;r>=1;r--){
        inv_shift_sub(s,u);
        for(int i=0;i<16;i++) u[i]^=rk[16*r+i];
        for(int c=0;c<4;c++) inv_mix_cols(u+4*c,t+4*c);
        memcpy(s,t,16);
    }
    inv_shift_sub(s,u);
    for(int i=0;i<16;i++) out[i]=(uint8_t)(u[i]^rk[i]);
}

/* ------------------------------------------------------------- parameters */
static const char* SEG_CT_B64[5] = {NULL,
    "I2c6TXU/Z1oCKnEQTWZUvg==",
    "RWaBo4ChEOM/i+MLy2NUpg==",
    "16GmtUINaYuN7f1RlBO5sQ==",
    "7CZlZjwCMGUb/TZm07b9dg=="};
static const char* SEG_IV[5] = {NULL,
    "few_n_far_btween","nocturnal_sugars","colors_on_leaves","seconds_of_dream"};

static int b64val(int c){
    if(c>='A'&&c<='Z') return c-'A';
    if(c>='a'&&c<='z') return c-'a'+26;
    if(c>='0'&&c<='9') return c-'0'+52;
    if(c=='+') return 62;
    if(c=='/') return 63;
    return -1;
}
static void b64decode(const char*s,uint8_t*out,int*n){
    int acc=0,bits=0,o=0;
    for(const char*p=s;*p&&*p!='=';p++){
        acc=(acc<<6)|b64val(*p); bits+=6;
        if(bits>=8){ bits-=8; out[o++]=(uint8_t)((acc>>bits)&0xff); }
    }
    *n=o;
}
static int hexnib(int c){
    if(c>='0'&&c<='9') return c-'0';
    if(c>='a'&&c<='f') return c-'a'+10;
    if(c>='A'&&c<='F') return c-'A'+10;
    return -1;
}
static void hexdecode(const char*s,uint8_t*out){
    size_t n=strlen(s)/2;
    for(size_t i=0;i<n;i++) out[i]=(uint8_t)(hexnib(s[2*i])*16+hexnib(s[2*i+1]));
}

static uint8_t CT[16], IV[16];
/* clue 3 is lowercased and 8 characters. The clue's own grid uses only w,a,s,d
   and the digits 1-9; 0 is included because a step count of 0 is a legitimate
   reading of "no movement", so the sweep must not quietly assume otherwise. */
static const char* ALPHA = "wasd0123456789";
#define NALPHA 14

static inline int test_key(const uint8_t*key,uint8_t*pt){
    uint8_t rk[240],out[16];
    aes256_expand(key,rk);
    aes256_decrypt_block(rk,CT,out);
    for(int i=8;i<16;i++) if((uint8_t)(out[i]^IV[i])!=0x08) return 0;
    if(pt) for(int i=0;i<16;i++) pt[i]=(uint8_t)(out[i]^IV[i]);
    return 1;
}
static void show_pt(const uint8_t*pt){
    printf("  super_key bytes 16-23 = ");
    for(int i=0;i<8;i++) printf("%02x",pt[i]);
    printf("  ascii8=%.*s\n",8,(const char*)pt);
}

/* ------------------------------------------------------------- list input */
static char (*LEFT)[25];  static int nleft;
static char (*RIGHT)[25]; static int nright;
static int read_list(const char*path,char (*buf)[25],int want,int*count){
    FILE*f=fopen(path,"r"); if(!f){ fprintf(stderr,"cannot open %s\n",path); exit(2); }
    char line[256]; int n=0, dropped=0;
    while(fgets(line,sizeof line,f)){
        size_t L=strlen(line); while(L&&(line[L-1]=='\n'||line[L-1]=='\r')) line[--L]=0;
        if(!L) continue;
        if((int)L!=want){ dropped++; continue; }
        for(int i=0;i<want;i++) buf[n][i]=(char)(line[i]>='A'&&line[i]<='Z'?line[i]+32:line[i]);
        buf[n][want]=0; n++;
    }
    fclose(f);
    if(dropped) fprintf(stderr,"%s: dropped %d line(s) not exactly %d chars\n",path,dropped,want);
    *count=n; return n;
}

/* --------------------------------------------------------------- witnesses */
#define MAXW 32
static uint8_t WKEY[MAXW][33]; /* 32 ASCII characters plus a NUL for printing */
static uint8_t WCT[MAXW][16]; static char WNAME[MAXW][32];
static int nw;
static void read_witnesses(const char*path){
    FILE*f=fopen(path,"r"); if(!f){ fprintf(stderr,"cannot open %s\n",path); exit(2); }
    char line[256];
    while(fgets(line,sizeof line,f) && nw<MAXW){
        char name[32],key[64],ct[64];
        if(sscanf(line,"%31s %63s %63s",name,key,ct)!=3) continue;
        if(strlen(key)!=32||strlen(ct)!=32){ fprintf(stderr,"bad witness line: %s",line); continue; }
        snprintf(WNAME[nw],32,"%s",name);
        memcpy(WKEY[nw],key,32); WKEY[nw][32]=0;
        hexdecode(ct,WCT[nw]);
        nw++;
    }
    fclose(f);
    if(!nw){ fprintf(stderr,"witness file %s has no usable lines\n",path); exit(2); }
}
static int verify_witnesses(void){
    int ok=0;
    for(int i=0;i<nw;i++){
        uint8_t pt[16], save[16];
        memcpy(save,CT,16);
        memcpy(CT,WCT[i],16);
        int hit=test_key(WKEY[i],pt);
        memcpy(CT,save,16);
        printf("witness %-10s key=%s  padding %s",WNAME[i],(const char*)WKEY[i],
               hit?"OK":"FAILED");
        if(hit){ show_pt(pt); ok++; } else printf("\n");
    }
    printf("witnesses re-found: %d/%d %s\n",ok,nw,ok==nw?"OK":"-- UNCERTIFIED");
    return ok;
}

/* ---------------------------------------------------------------- selftest */
static int selftest(void){
    int ok=1;
    /* Re-derive the S-box from its definition and require all 256 bytes. */
    {
        uint8_t inv_tbl[256], S[256];
        int have_all=1;
        memset(inv_tbl,0,sizeof inv_tbl);   /* inv_tbl[0] = 0: never set below */
        for(int a=1;a<256;a++){
            int found=0;
            for(int b=1;b<256;b++){
                uint8_t r=0, aa=(uint8_t)a, bb=(uint8_t)b;
                while(bb){ if(bb&1) r^=aa; aa=MUL1[aa]; bb>>=1; }
                if(r==1){ inv_tbl[a]=(uint8_t)b; found=1; break; }
            }
            if(!found){ printf("  no GF(2^8) inverse for %d\n",a); have_all=0; }
        }
        for(int i=0;i<256;i++){
            uint8_t x=inv_tbl[i], y=x, acc=x;
            for(int sh=1;sh<=4;sh++){ y=(uint8_t)((y<<1)|(y>>7)); acc^=y; }
            S[i]=(uint8_t)(acc^0x63);
        }
        int t=have_all;
        for(int i=0;i<256;i++) if(S[i]!=SBOX[i]) t=0;
        printf("S-box equals affine(GF(2^8) inverse), 256/256      -> %s\n",t?"OK":"FAIL");
        ok&=t;
        int u=1; for(int i=0;i<256;i++) if(ISBOX[SBOX[i]]!=i) u=0;
        printf("ISBOX is the exact inverse of SBOX, 256/256       -> %s\n",u?"OK":"FAIL");
        ok&=u;
        int v=1; for(int i=0;i<256;i++) if(SBOX[ISBOX[i]]!=i) v=0;
        printf("SBOX is the exact inverse of ISBOX, 256/256       -> %s\n",v?"OK":"FAIL");
        ok&=v;
    }
    /* a pycryptodome vector, supplied by tools/seg3_witnesses.py --selftest */
    {
        uint8_t key[32],pt[16],ct[16],out[16],rk[240];
        hexdecode("1bad420c0aa898aa5485483e92cd5d3a0af14dd7516d148eb6602ad6434bf064",key);
        hexdecode("502414db284e8198f5bf7af67344af2a",pt);
        hexdecode("ff741e83ed1f12662dbebacb7cb56483",ct);
        aes256_expand(key,rk);
        aes256_decrypt_block(rk,ct,out);
        int t=1; for(int i=0;i<16;i++) if(out[i]!=pt[i]) t=0;
        printf("pycryptodome AES-256 decrypt                         -> %s\n",t?"OK":"FAIL");
        ok&=t;
    }
    /* the four real segment ciphertexts: 16 bytes, 16-char IV, and base64
       canonicity (a 16-byte value leaves only 2 useful bits in character 22,
       so it can only be A, Q, g or w) */
    {
        int t=1;
        for(int s=1;s<=4;s++){
            uint8_t b[32]; int n=0; b64decode(SEG_CT_B64[s],b,&n);
            int c22=SEG_CT_B64[s][21];
            int good=n==16 && strlen(SEG_IV[s])==16 && strchr("AQgw",c22)!=NULL;
            printf("segment %d  ct=%d bytes  iv=%zu chars  base64[21]=%c      -> %s\n",
                   s,n,strlen(SEG_IV[s]),c22,good?"OK":"FAIL");
            t&=good;
        }
        printf("segment parameters                                  -> %s\n",t?"OK":"FAIL");
        ok&=t;
    }
    /* an arbitrary key must be rejected */
    {
        int n; b64decode(SEG_CT_B64[3],CT,&n); memcpy(IV,SEG_IV[3],16);
        uint8_t key[32];
        for(int i=0;i<32;i++) key[i]=(uint8_t)(i*7+1);
        int t = test_key(key,NULL) ? 0 : 1;
        printf("an arbitrary 32-byte key is rejected                 -> %s\n",t?"OK":"FAIL");
        ok&=t;
    }
    printf("%s\n",ok?"SELFTEST OK":"SELFTEST FAILED, conclude nothing");
    return ok;
}

/* --------------------------------------------------------- cross-check mode */
static int mode_pt(const char*path){
    int n; b64decode(SEG_CT_B64[3],CT,&n); memcpy(IV,SEG_IV[3],16);
    FILE*f=fopen(path,"r"); if(!f){ fprintf(stderr,"cannot open %s\n",path); return 2; }
    char line[256]; long count=0;
    while(fgets(line,sizeof line,f)){
        size_t L=strlen(line); while(L&&(line[L-1]=='\n'||line[L-1]=='\r')) line[--L]=0;
        if(!L) continue;
        if(L!=32){ fprintf(stderr,"skipping %zu-char line\n",L); continue; }
        uint8_t key[32]; memcpy(key,line,32);
        uint8_t rk[240],out[16],pt[16];
        aes256_expand(key,rk);
        aes256_decrypt_block(rk,CT,out);
        for(int i=0;i<16;i++) pt[i]=(uint8_t)(out[i]^IV[i]);
        printf("%s ",line);
        for(int i=0;i<16;i++) printf("%02x",pt[i]);
        printf(" %s\n", (memcmp(pt+8,"\x08\x08\x08\x08\x08\x08\x08\x08",8)==0)?"PAD":"");
        count++;
    }
    fclose(f);
    fprintf(stderr,"printed %ld plaintexts\n",count);
    return 0;
}

/* --------------------------------------------------------------- list mode */
static int mode_list(const char*wf,const char*lf,const char*rf){
    int n; b64decode(SEG_CT_B64[3],CT,&n); memcpy(IV,SEG_IV[3],16);
    read_witnesses(wf);
    if(verify_witnesses()!=nw) return 1;

    LEFT =calloc(400000,sizeof *LEFT);
    RIGHT=calloc(400000,sizeof *RIGHT);
    if(!LEFT||!RIGHT){ fprintf(stderr,"out of memory\n"); return 2; }
    read_list(lf,LEFT,8,&nleft);
    read_list(rf,RIGHT,24,&nright);
    if(!nleft||!nright){ printf("nothing to test\n"); return 0; }
    fprintf(stderr,"list mode: %d lefts x %d rights = %lld pairs\n",
            nleft,nright,(long long)nleft*nright);

    unsigned long long tried=0; int hits=0;
    for(int i=0;i<nleft;i++)
        for(int j=0;j<nright;j++){
            uint8_t key[32]; memcpy(key,LEFT[i],8); memcpy(key+8,RIGHT[j],24);
            uint8_t pt[16];
            tried++;
            if(test_key(key,pt)){
                hits++;
                printf("HIT  wasd=%s  ship=%s\n",LEFT[i],RIGHT[j]);
                show_pt(pt); fflush(stdout);
            }
        }
    printf("list: %llu pairs, %d hit(s)\n",tried,hits);
    printf("RESULT %s\n",hits?"HIT":"no match");
    return hits?0:1;
}

/* -------------------------------------------------------------- alpha mode */
static int mode_alpha(const char*wf,const char*rf,long max_rights){
    int n; b64decode(SEG_CT_B64[3],CT,&n); memcpy(IV,SEG_IV[3],16);
    read_witnesses(wf);
    if(verify_witnesses()!=nw) return 1;

    RIGHT=calloc(400000,sizeof *RIGHT);
    if(!RIGHT){ fprintf(stderr,"out of memory\n"); return 2; }
    read_list(rf,RIGHT,24,&nright);
    if(max_rights>0 && nright>max_rights) nright=(int)max_rights;
    if(!nright){ printf("nothing to test\n"); return 0; }
    fprintf(stderr,"alpha mode: %d rights x 14^8 = %.4g keys\n",
            nright,(double)nright*1475789056.0);

    /* report which witnesses sit inside the stream this sweep will traverse */
    int wi=nright/2;
    for(int i=0;i<nw;i++)
        if(!memcmp(WKEY[i],"wasdwasd",8) && !memcmp(WKEY[i]+8,RIGHT[wi],24))
            printf("witness '%s' lies inside the alpha sweep stream\n",WNAME[i]);

    unsigned long long total=0; int hits=0;
    uint8_t idx[8];
    for(int j=0;j<nright;j++){
        uint8_t key[32]; memcpy(key+8,RIGHT[j],24);
        memset(idx,0,8);
        for(;;){
            for(int k=0;k<8;k++) key[k]=(uint8_t)ALPHA[idx[k]];
            total++;
            uint8_t pt[16];
            if(test_key(key,pt)){
                hits++;
                printf("HIT  wasd=%.8s  ship=%s\n",(const char*)key,RIGHT[j]);
                show_pt(pt); fflush(stdout);
            }
            int d=7;
            while(d>=0){ if(idx[d]<NALPHA-1){ idx[d]++; break; } idx[d]=0; d--; }
            if(d<0) break;
        }
        printf("  [%d/%d] ship=%s  %llu keys, %d hits\n",j+1,nright,RIGHT[j],total,hits);
        fflush(stdout);
    }
    printf("alpha: %llu keys, %d hit(s)\n",total,hits);
    printf("RESULT %s\n",hits?"HIT":"no match");
    return hits?0:1;
}

int main(int argc,char**argv){
    build_tables();
    if(argc<2){ fprintf(stderr,
        "usage: seg3_cross selftest\n"
        "       seg3_cross pt    <keys.txt>\n"
        "       seg3_cross list  <witnesses.txt> <lefts.txt> <rights.txt>\n"
        "       seg3_cross alpha <witnesses.txt> <rights.txt> [max_rights]\n"); return 2; }
    if(!strcmp(argv[1],"selftest")) return selftest()?0:1;
    if(!strcmp(argv[1],"pt")&&argc==3)    return mode_pt(argv[2]);
    if(!strcmp(argv[1],"list")&&argc==5)  return mode_list(argv[2],argv[3],argv[4]);
    if(!strcmp(argv[1],"alpha")&&argc>=4) return mode_alpha(argv[2],argv[3],argc>4?atol(argv[4]):0);
    fprintf(stderr,"bad arguments\n");
    return 2;
}